version: '3.8'  # تحدد نسخة صيغة Docker Compose
services:       # تعريف الخدمات (الحاويات)
  postgres:     # اسم الخدمة
    image: postgres  # الصورة التي ستستخدمها الحاوية
    container_name: my_postgres  # اسم الحاوية (اختياري)
    environment:    # متغيرات البيئة داخل الحاوية
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: ny_taxi
    ports:          # توجيه المنافذ (الخارجية:الداخلية)
      - "5433:5432"
    volumes:        # التخزين (المضيف:داخل الحاوية)
      - C:\Users\abdel\SQL_docker\ny_taxi_postgres_data:/var/lib/postgresql/data

  pgadmin:      # اسم خدمة pgAdmin
    image: dpage/pgadmin4  # الصورة التي ستستخدمها الحاوية
    container_name: my_pgadmin  # اسم الحاوية (اختياري)
    environment:   # متغيرات البيئة داخل الحاوية
      PGADMIN_DEFAULT_EMAIL: admin@admin.com  # البريد الإلكتروني الافتراضي لتسجيل الدخول
      PGADMIN_DEFAULT_PASSWORD: admin123      # كلمة المرور الافتراضية لتسجيل الدخول
    ports:         # توجيه المنافذ
      - "5050:80"  # منفذ pgAdmin


